name: noteme
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  cloud_firestore: ^4.15.5
  share_plus: ^7.2.2
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.9



flutter:
  uses-material-design: true
